# Generated by Django 5.1.3 on 2024-11-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FetchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=4096)),
                ('raw_json', models.JSONField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Parsing'), (2, 'Finished'), (3, 'Error')], default=0)),
            ],
        ),
    ]
