# Generated by Django 5.1.3 on 2024-11-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchitem',
            name='raw_json',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='fetchitem',
            name='url',
            field=models.CharField(max_length=4096, unique=True),
        ),
    ]
