# Generated by Django 5.1.3 on 2024-11-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0002_alter_fetchitem_raw_json_alter_fetchitem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchitem',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
