# Generated by Django 5.1.3 on 2024-11-09 13:39

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0003_fetchitem_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_image', models.CharField(max_length=4096, unique=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='TagCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_id', models.CharField(max_length=64, unique=True)),
                ('foreign_path', models.CharField(max_length=4096)),
                ('tag', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=256)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsing.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(default='', max_length=1024)),
                ('description', models.TextField(default='')),
                ('ingredient', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048), default=list, size=None)),
                ('instructions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2048), default=list, size=None)),
                ('fetch_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsing.fetchitem')),
                ('images', models.ManyToManyField(to='parsing.image')),
                ('tag_clouds', models.ManyToManyField(to='parsing.tagcloud')),
            ],
        ),
    ]
