# Generated by Django 5.1.3 on 2024-11-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0004_image_tagcloud_tag_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='active_time',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='recipe',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='serving_size',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_time',
            field=models.CharField(default='', max_length=128),
        ),
    ]
