# Generated by Django 5.1.3 on 2024-11-10 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing', '0009_remove_recipe_tag_clouds_delete_tagcloud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_weight', models.PositiveIntegerField(blank=True, null=True)),
                ('goal_weight', models.PositiveIntegerField(blank=True, null=True)),
                ('diet_goal', models.CharField(blank=True, choices=[('get_inspiration', 'Get inspiration'), ('eat_healthy', 'Eat healthy'), ('loose_weight', 'Loose weight'), ('build_muscles', 'Build muscles')], max_length=64, null=True)),
                ('diet_type', models.CharField(blank=True, choices=[('i_eat_everything', 'I eat everything'), ('pescatarian', 'Pescatarian'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan')], max_length=64, null=True)),
                ('allegries', models.ManyToManyField(related_name='allergic_users', to='parsing.tag')),
                ('preferences', models.ManyToManyField(related_name='prerence_users', to='parsing.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_time', models.CharField(choices=[('breakfast', 'Breakfast'), ('brunch', 'Brunch'), ('dinner', 'Dinner'), ('lunch', 'Lunch')], max_length=64)),
                ('diet_type', models.CharField(choices=[('i_eat_everything', 'I eat everything'), ('pescatarian', 'Pescatarian'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan')], max_length=64)),
                ('diet_goal', models.CharField(choices=[('get_inspiration', 'Get inspiration'), ('eat_healthy', 'Eat healthy'), ('loose_weight', 'Loose weight'), ('build_muscles', 'Build muscles')], max_length=64)),
                ('tags', models.ManyToManyField(to='parsing.tag')),
            ],
            options={
                'unique_together': {('meal_time', 'diet_type', 'diet_goal')},
            },
        ),
    ]
